---
- name: Seleccionar actualizaciones específicas en Windows
  hosts: all
  gather_facts: no
  collections:
    - ansible.windows

  vars:
    actualizaciones_a_instalar: []

  tasks:

    - name: Buscar actualizaciones disponibles
      win_updates:
        state: searched
      register: actualizaciones_disponibles

    - name: Ver estructura de actualizaciones_disponibles.updates
      debug:
        var: actualizaciones_disponibles.updates[0]

    - name: Mostrar todas las actualizaciones encontradas
      debug:
        msg: |
          {% for update in actualizaciones_disponibles.updates %}
          - {{ update }}
          {% endfor %}


    - name: Filtrar actualizaciones seleccionadas por KB
      set_fact:
        updates_filtradas: >-
          {{ actualizaciones_disponibles.updates
             | selectattr('kb_article_ids', 'defined')
             | selectattr('kb_article_ids', 'intersect', actualizaciones_a_instalar)
             | list }}

    - name: Mostrar actualizaciones que se instalarán
      debug:
        msg: >
          Se instalarán las siguientes actualizaciones:
          {{ updates_filtradas | map(attribute='title') | list }}

    - name: Instalar actualizaciones por KB específicas
      win_updates:
        category_names:
          - SecurityUpdates
        kb_article_ids: "{{ actualizaciones_a_instalar }}"
        state: installed
