---
- name: Listar actualizaciones pendientes en Windows
  hosts: all
  gather_facts: no
  tasks:

    - name: Buscar actualizaciones disponibles (todas las categorías)
      ansible.windows.win_updates:
        state: searched
      register: actualizaciones_disponibles

    - name: Mostrar lista de actualizaciones encontradas
      debug:
        msg: >-
          {% for update in actualizaciones_disponibles.updates | default([]) %}
          - Título: {{ update.title }}
            KB: {{ update.kb_article_ids | default([]) | join(', ') }}
          {% else %}
          No hay actualizaciones disponibles.
          {% endfor %}
      when: actualizaciones_disponibles.updates is defined
