---
- name: Buscar e instalar actualizaciones seleccionadas
  hosts: all
  gather_facts: no
  vars:
    categorias_instalacion:
      - SecurityUpdates
      - CriticalUpdates
  tasks:

    - name: Buscar actualizaciones disponibles
      ansible.windows.win_updates:
        category_names: "{{ categorias_instalacion }}"
        state: searched
      register: actualizaciones_disponibles

    - name: No se encontraron actualizaciones
      debug:
        msg: "No hay actualizaciones disponibles para instalar."
      when: actualizaciones_disponibles.updates is not defined or actualizaciones_disponibles.updates | length == 0

    - name: Mostrar lista de actualizaciones encontradas
      debug:
        msg: >-
          {% for update in actualizaciones_disponibles.updates | default([]) %}
          - Título: {{ update.title() }}
            KB: {{ update.kb_article_ids | default([]) | join(', ') }}
          {% endfor %}
      when: actualizaciones_disponibles.updates is defined and actualizaciones_disponibles.updates | length > 0

    - name: Validar si hay actualizaciones encontradas
      debug:
        msg: "No hay actualizaciones disponibles."
      when: actualizaciones_disponibles.updates | length == 0

    - name: Instalar actualizaciones seleccionadas (por KB)
      ansible.windows.win_updates:
        category_names: "{{ categorias_instalacion }}"
        kb_article_ids: "{{ kb_a_instalar }}"
        reboot: true
      when: kb_a_instalar is defined
