---
- name: Verificar y aplicar actualizaciones de seguridad (Ubuntu y AlmaLinux)
  hosts: all
  become: true
  gather_facts: yes

  vars:
    instalar_actualizaciones_ubuntu: "no"
    instalar_actualizaciones_almalinux: "no"

  tasks:

    # Validaciones
    - name: Validar valor de instalar_actualizaciones_ubuntu
      fail:
        msg: "Valor inválido para instalar_actualizaciones_ubuntu (usa 'si' o 'no')"
      when: instalar_actualizaciones_ubuntu not in ["si", "no"]

    - name: Validar valor de instalar_actualizaciones_almalinux
      fail:
        msg: "Valor inválido para instalar_actualizaciones_almalinux (usa 'si' o 'no')"
      when: instalar_actualizaciones_almalinux not in ["si", "no"]

    # --------------------
    # Ubuntu
    # --------------------
    - name: Verificar actualizaciones de seguridad en Ubuntu
      shell: apt list --upgradable 2>/dev/null
      register: ubuntu_security_updates
      changed_when: false
      when: ansible_facts['os_family'] == "Debian"
      
    - name: Actualizaciones pendientes
      set_fact:
          resumen_almalinux: "{{ ubuntu_security_updates.stdout_lines | select('match', '^ALSA') | list }}"
    - name: Mostrar resumen
      debug:
        msg: "Se Encontraron {{ resumen_almalinux | length }} actualizaciones de seguridad."


    - name: Aplicar actualizaciones de seguridad en Ubuntu
      apt:
        upgrade: dist
        update_cache: yes
      when:
        - ansible_facts['os_family'] == "Debian"
        - instalar_actualizaciones_ubuntu == "si"

    - name: Requiere reinicio
      stat:
        path: /var/run/reboot-required
      register: ubuntu_reboot_check
      when: ansible_facts['os_family'] == "Debian"

    - name: Requiere reinicio
      debug:
        msg: "Ubuntu requiere reinicio"
      when:
        - ansible_facts['os_family'] == "Debian"
        - ubuntu_reboot_check.stat.exists

    - name: Requiere reinicio
      debug:
        msg: "Ubuntu no requiere reinicio"
      when:
        - ansible_facts['os_family'] == "Debian"
        - not ubuntu_reboot_check.stat.exists

    # --------------------
    # AlmaLinux
    # --------------------
    - name: Verificar actualizaciones de seguridad en AlmaLinux
      shell: dnf makecache --refresh && dnf updateinfo list security
      register: almalinux_security_updates
      changed_when: false
      when: ansible_facts['os_family'] == "RedHat"

    - name: Actualizaciones pendientes
      set_fact:
        resumen_almalinux: "{{ almalinux_security_updates.stdout_lines | select('match', '^ALSA') | list }}"
    - name: Mostrar resumen
      debug:
        msg: "Se Encontraron {{ resumen_almalinux | length }} actualizaciones de seguridad."
  
    - name: Aplicar actualizaciones de seguridad
      shell: dnf update --security -y
      when:
        - ansible_facts['os_family'] == "RedHat"
        - instalar_actualizaciones_almalinux == "si"

    - name: Verificar si AlmaLinux requiere reinicio
      shell: needs-restarting -r; echo $?
      register: almalinux_reboot_check
      changed_when: false
      when: ansible_facts['os_family'] == "RedHat"

    - name: Requiere reinicio
      debug:
        msg: "AlmaLinux requiere reinicio"
      when:
        - ansible_facts['os_family'] == "RedHat"
        - almalinux_reboot_check.stdout != "0"

    - name: Requiere reinicio
      debug:
        msg: "AlmaLinux no requiere reinicio"
      when:
        - ansible_facts['os_family'] == "RedHat"
        - almalinux_reboot_check.stdout == "0"
