---
- name: Instalar Protect Agent y configurar entorno
  hosts: all
  become: yes

  vars:
    remote_host: 192.193.1.241
    remote_script_path: /home/sbxalocal/PROTECTAgentInstaller.sh
    local_script_path: /home/sbxalocal/PROTECTAgentInstaller.sh

  tasks:

    - name: Instalar policycoreutils-devel
      dnf:
        name: policycoreutils-devel
        state: present

    - name: Abrir puertos 2222/tcp y 3128/tcp en el firewall
      firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        state: enabled
        immediate: yes
      loop:
        - 2222
        - 3128

    - name: Asegurar que firewalld esté activo
      systemd:
        name: firewalld
        state: started
        enabled: true

    - name: Copiar script desde 192.193.1.241 al host actual
      fetch:
        src: /home/sbxalocal/PROTECTAgentInstaller.sh
        dest: /home/ansible/
        flat: yes
      delegate_to: 192.193.1.241
      become: false
      remote_user: ansible


    - name: Dar permisos de ejecución al script
      file:
        path: "{{ local_script_path }}"
        mode: '0755'
        state: file

    - name: Ejecutar el script
      command: "{{ local_script_path }}"
